---
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:17.9.0-ce.0
    hostname: "gitlab.example.com"
    ports:
      - 80:80
      - 443:443
      - 22:22
    volumes:
      - ./config/:/etc/gitlab
      - ./logs/:/var/log/gitlab
      - ./data/:/var/opt/gitlab
      - ./step/ssl:/etc/gitlab/ssl:z
    depends_on:
      - acme
    #restart: unless-stopped

  acme:
    container_name: git-acme
    image: smallstep/step-ca:0.28.1
    #hostname: "acme.example.com"
    env_file:
      - ./resources/step.env
    ports:
      - 9000:9000
    volumes:
      - ./step:/home/step
      - ./step/ssl:/home/step/ssl:z
    restart: unless-stopped

#volumes:
 # step: {}