---
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:17.9.0-ce.0
    hostname: "gitlab.test"
    ports:
      - 80:80
      - 443:443
      - 22:22
    environment:
      - SUBJECT=localhost
    volumes:
      - ./config/:/etc/gitlab
      - ./logs/:/var/log/gitlab
      - ./data/:/var/opt/gitlab
      - ./step/config/defaults.json:/defaults.json:z
      - ./step/secrets/password:/password:z
      - ./resources/cmd.sh:/cmd.sh
    command: ["/cmd.sh"]
    depends_on:
      - acme
    restart: unless-stopped

  acme:
    container_name: git-acme
    image: smallstep/step-ca:0.28.1
    env_file:
      - ./resources/step.env
    volumes:
      - ./step:/home/step
    restart: unless-stopped

#volumes:
 # step: {}
